FROM node:18-slim

USER root

RUN npm install -g @nestjs/cli@8.0.0

COPY /apps/kanbam/package*.json ./
COPY /apps/kanbam/tsconfig.build.json ./
COPY /apps/kanbam/tsconfig.json ./

COPY . .

WORKDIR /usr/src/app