version: '3'

services:
  main_receiver:
    container_name: main_receiver
    build:
      context: ./
      dockerfile: ./Dockerfile.Task
    volumes:
      - ./apps/main-receiver/:/usr/src/app/
    networks:
      - monorepo_network
    ports:
      - 3002:3002      
      - 9230:9229
    command: "sh -c 'npm install && npm run start:debug'"

 networks:
  monorepo_network:
    driver: bridge
